-- ============================================================
-- STALE — DO NOT RUN
-- The canonical schema is deployed via meridian-migration-v2.sql
-- + meridian-supplement.sql (case_events, bar_sessions)
-- This file is kept for git history only.
-- ============================================================
